### ISSUE TITLE
Minor issue with log entry

### ISSUE THREAD

**Issue by Tipalo** [hassio-addons/addon-wireguard#186]
# Issue
> misleading data shown in log file

## Expected 
>Port number shown in add-on log to reflect  port number entered in configuration

## Actual behavior
>log displays port 51820 as being monitored instead of the actual port set in the config
>VPN is working with alternate port so looks likes does not effect the behavior of the VPN 

## Steps to reproduce
enter alternate port number, restart,  watch log
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The addon runs as a container, on a different network, the messages you see are produced from Wireguard itself, which is only listening on that port, and has no knowledge that a different port is being forwarded.

This is caused by running in a container, and there isn't anything that can be done to fix it, it would be no different to ask HomeAssistant itself to be aware of the port you advertise via a Reverse Proxy somewhere, or for example the port you decide to forward on a network device.
