### ISSUE TITLE
HomeKit

### ISSUE THREAD

**Issue by pasqui7** [hassio-addons/addon-wireguard#189]
Hi guys, I had configured WireGuard on my raspberry with hassio. Works perfectly, but I can't control HomeKit when I stay outside my network. I don't have any bridge like Apple TV, iPad or HomePod. Can you help me to fix this issue?

**Comment by PanicRide** [comment]
This doesn't have anything to do with the wireguard addon, but I can tell you that the protocols used by HomeKit (Bonjour/mDNS) don't work over regular VPN connections because they rely on you being able to send and receive Ethernet frames on the local network, not just TCP/UDP/IP.

Your best option is to use Home Assistant when away because it's on your home network and can relay commands to your HomeKit devices for you.

If you need to use the Apple Home app while away, you need to have a Apple TV or iPad on your home network acting as a HomeKit Hub which will relay commands through Apple's cloud for you.

**Comment by pasqui7** [comment]
Ok! Really thanks for explained! Can I ask somethings about sky go app and sky q with WireGuard?
