### ISSUE TITLE
Web UI support?

### ISSUE THREAD

**Issue by scrytch** [hassio-addons/addon-wireguard#51]
Hi,

Everything working well. Just wanted to ask if possible to incorporate the web ui from https://github.com/ngoduykhanh/wireguard-ui into the HASSIO wireguard addon?

Would love to be able to do changes quickly via ui rather than shell.

Thanks,
Shane.

**Comment by theseal** [comment]
I tried to create an add-on with [wg-ui](https://github.com/EmbarkStudios/wg-ui/) for the similar reason but run in to [an issue](https://github.com/EmbarkStudios/wg-ui/issues/94). 

[wireguard-ui](https://github.com/ngoduykhanh/wireguard-ui) doesn't seem as polished as [wg-ui](https://github.com/EmbarkStudios/wg-ui/) but is probably a good alternative since I can't get wg-ui to work. Not sure if that would replace the wireguard addon or just be another alternative.
