### ISSUE TITLE
sysctl keys can't be changed because it's read-only

### ISSUE THREAD

**Issue by rderensy** [hassio-addons/addon-wireguard#52]
# Problem/Motivation

When running Wireguard on Hassio, it tries to enable the key `net.ipv4.conf.all.src_valid_mark` but it can't because `sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system`

## Expected behavior

Enable the key and create the interface.

## Actual behavior

The error is thrown and wg0 isn't created

## Steps to reproduce

I just installed, configured and restarted the add-on. I can't change that key via `/etc/resolv.conf` either and `/proc/sys/net/ipv4/conf/all/src_valid_mark` is unwritable

**Comment by KalininAndreyVictorovich** [comment]
Occurs on my system as well.
Seams like this problem is in upstream image: https://forums.docker.com/t/sysctl-error-setting-key-net-ipv4-conf-all-src-valid-mark-read-only-file-system/92567/8. Still, the extension is completely nonfunctional at this state.

here's the log:
```
-----------------------------------------------------------
 Add-on: WireGuard
 Fast, modern, secure VPN tunnel
-----------------------------------------------------------
 Add-on version: 0.3.2
 You are running the latest version of this add-on.
 System: HassOS 4.15  (armv7 / raspberrypi3)
 Home Assistant Core: 0.116.4
 Home Assistant Supervisor: 249
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] config.sh: executing... 
[cont-init.d] config.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:31:59] INFO: Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.19.49.2/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
```

**Comment by Underknowledge** [comment]
I think the error is only occurring when you define a catch-all
The platforms you're using would be interesting. 
Same behaviour on a Debian Supervised install. 
@KalininAndreyVictorovich I think when set  `allowed_ips` to `[] ` ,this error were coming here for, wont come up and ll do the same as a catchall

**Comment by rderensy** [comment]
I tried with Home Assistant OS and Supervised on Debian and I have the problem on both. Though you are right, configuring `allowed_ips: []` doesn't throw this error

**Comment by Underknowledge** [comment]
I just goggled a little and found out that multiple docker builds are facing this issue 
https://forums.docker.com/t/sysctl-error-setting-key-net-ipv4-conf-all-src-valid-mark-read-only-file-system/92567/8

a little background information is providing this article 
https://www.theurbanpenguin.com/rp_filter-and-lpic-3-linux-security/

so when I type sysctl -ar 'src_valid_mark' on the host I get 
```
[root@debian-homeassistant ~] :sysctl -ar 'src_valid_mark'
net.ipv4.conf.all.src_valid_mark = 0
net.ipv4.conf.br-9575432e7d39.src_valid_mark = 0
net.ipv4.conf.default.src_valid_mark = 0
net.ipv4.conf.docker0.src_valid_mark = 0
net.ipv4.conf.ens192.src_valid_mark = 0
net.ipv4.conf.hassio.src_valid_mark = 0
net.ipv4.conf.lo.src_valid_mark = 0
net.ipv4.conf.veth12cc582.src_valid_mark = 0
...
net.ipv4.conf.vethf665e27.src_valid_mark = 0
```
poke it with a stick 
` [root@debian-homeassistant ~] :echo 1 > /proc/sys/net/ipv4/conf/all/src_valid_mark`

 adding back the catchall config aaaand 
```bash

[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.27.66.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] ip -4 route add 10.0.0.0/22 dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
```
Bummer :D wireguard itself try's to add the flag to the file.
But as already mentioned, thats only true for a catchall (0.0.0.0) because when you pass a subnet wireguard will do a 
`[#] ip -4 route add 10.0.0.0/22 dev wg0` which wont fail. 
From here I see 4 outcomes 
- privileged mode (very bad thing to do imo) 
- mount `/proc/sys/net/ipv4/conf/all/` RW in the container ( not sure if this is even possible)  
- ignore catchall around [here](https://github.com/hassio-addons/addon-wireguard/blob/master/wireguard/rootfs/etc/cont-init.d/config.sh#L265) that wireguard(?, maybe something diffrent..) wont trigger to set the flag
- just mention it in the readme ( atm I would go for that :see_no_evil:  )

**Comment by einzelband** [comment]
I have the same problem.
Looks like other projects does / did also have/had this problem: https://github.com/linuxserver/docker-wireguard/issues/15
Here for me it looks like a change "Use openresolv instead of resolvconf" fixed the problem.
But I guess this addon already use openresolv. (I am not so familiar with docker, sorry)
Can somebody confirm that? Maybe a newer Version will fix this?

**Comment by pahansen95** [comment]
FWIW

Somewhere along the line sysctl started returning a non zero exit code for the command if the filesystem is read only:

`sysctl -q net.ipv4.conf.all.src_valid_mark=1`

Run that in an ubuntu 18.04 container & you'll see it returns 0.

Run that in an ubuntu 20.04 container & you'll see it returns 255.

In wq-quick, in the `add_default` function when processing the `0.0.0.0/0` ipv4 address this line is eventually executed

`[[ $proto == -4 ]] && cmd sysctl -q net.ipv4.conf.all.src_valid_mark=1`

Since `set -e -o pipefail` is set in the script, it exits on error which is trapped to tear down everything it just built.

`trap 'del_if; exit' INT TERM EXIT`
